version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./src:/src
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - docker-network
    php:
        image: php:fpm
        volumes:
            - ./src:/src
        networks:
            - docker-network
    db:
        image: mariadb:latest
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: test123
        networks:
            - docker-network

networks:
    docker-network:
        driver: bridge
